/** @type {import('tailwindcss').Config} */

// --step--2: clamp(0.39rem, calc(0.36rem + 0.15vw), 0.5rem);
// --step--1: clamp(0.58rem, calc(0.54rem + 0.23vw), 0.75rem);
// --step-0: clamp(0.95rem, calc(0.81rem + 0.34vw), 1.05rem);
// --step-1: clamp(1.31rem, calc(1.21rem + 0.51vw), 1.69rem);
// --step-2: clamp(1.97rem, calc(1.82rem + 0.76vw), 2.53rem);
// --step-3: clamp(2.95rem, calc(2.72rem + 1.14vw), 3.8rem);
// --step-4: clamp(4.43rem, calc(4.09rem + 1.72vw), 5.7rem);
// --step-5: clamp(6.64rem, calc(6.13rem + 2.57vw), 8.54rem);

const fontSizes = {
  xs: "clamp(0.39rem, calc(0.36rem + 0.15vw), 0.5rem)",
  sm: "clamp(0.58rem, calc(0.54rem + 0.23vw), 0.75rem)",
  base: "clamp(0.95rem, calc(0.81rem + 0.34vw), 1.05rem)",
  DEFAULT: "clamp(0.95rem, calc(0.81rem + 0.34vw), 1.05rem)",
  lg: "clamp(1.31rem, calc(1.21rem + 0.51vw), 1.69rem)",
  xl: "clamp(1.97rem, calc(1.82rem + 0.76vw), 2.53rem)",
  "2xl": "clamp(2.95rem, calc(2.72rem + 1.14vw), 3.8rem)",
  "3xl": "clamp(4.43rem, calc(4.09rem + 1.72vw), 5.7rem)",
  "4xl": "clamp(6.64rem, calc(6.13rem + 2.57vw), 8.54rem)",
};

//   /* Space 3xs: 4px → 5px */
//   --space-3xs: clamp(0.25rem, calc(0.23rem + 0.08vw), 0.31rem);

//   /* Space 2xs: 8px → 9px */
//   --space-2xs: clamp(0.5rem, calc(0.48rem + 0.08vw), 0.56rem);

//   /* Space xs: 12px → 14px */
//   --space-xs: clamp(0.75rem, calc(0.72rem + 0.16vw), 0.88rem);

//   /* Space s: 16px → 18px */
//   --space-s: clamp(1rem, calc(0.97rem + 0.16vw), 1.13rem);

//   /* Space m: 24px → 27px */
//   --space-m: clamp(1.5rem, calc(1.45rem + 0.23vw), 1.69rem);

//   /* Space l: 32px → 36px */
//   --space-l: clamp(2rem, calc(1.94rem + 0.31vw), 2.25rem);

//   /* Space xl: 48px → 54px */
//   --space-xl: clamp(3rem, calc(2.91rem + 0.47vw), 3.38rem);

//   /* Space 2xl: 64px → 72px */
//   --space-2xl: clamp(4rem, calc(3.88rem + 0.63vw), 4.5rem);

//   /* Space 3xl: 96px → 108px */
//   --space-3xl: clamp(6rem, calc(5.81rem + 0.94vw), 6.75rem);

const spacings = {
  "3xs": "clamp(0.25rem, calc(0.23rem + 0.08vw), 0.31rem)",
  "2xs": "clamp(0.5rem, calc(0.48rem + 0.08vw), 0.56rem)",
  xs: "clamp(0.75rem, calc(0.72rem + 0.16vw), 0.88rem)",
  sm: "clamp(1rem, calc(0.97rem + 0.16vw), 1.13rem)",
  md: "clamp(1.5rem, calc(1.45rem + 0.23vw), 1.69rem)",
  lg: "clamp(2rem, calc(1.94rem + 0.31vw), 2.25rem)",
  xl: "clamp(3rem, calc(2.91rem + 0.47vw), 3.38rem)",
  "2xl": "clamp(4rem, calc(3.88rem + 0.63vw), 4.5rem)",
  "3xl": "clamp(6rem, calc(5.81rem + 0.94vw), 6.75rem)",
};

const defaultTheme = require("tailwindcss/defaultTheme");
module.exports = {
  darkMode: "class",
  corePlugins: {
    preflight: false,
  },
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        base: {
          light: "#f3f3f3",
          dark: "#030303",
        },
        gray: {
          25: "#fafafa",
          50: "#f5f5f5",
          100: "#efefef",
          200: "#dddddd",
          300: "#c3c4c3",
          400: "#b0b1b1",
          500: "#878888",
          600: "#6c6d6d",
          700: "#404141",
          800: "#222222",
          900: "#121313",
        },
        emerald: {
          25: "#edfaf5",
          50: "#dcfbf3",
          100: "#b9ffee",
          200: "#9bffe6",
          300: "#7affdf",
          400: "#5effd7",
          500: "#48e8c0",
          600: "#3ab597",
          700: "#318570",
          800: "#246354",
          900: "#1a473c",
        },
        indigo: {
          25: "#E1E8FF",
          50: "#B7C7FF",
          100: "#87A1FF",
          200: "#6384FF",
          300: "#3e67ff",
          400: "#194aff",
          500: "#153dd1",
          600: "#102fa3",
          700: "#0c2275",
          800: "#111b40",
          900: "#131621",
        },
        purple: {
          25: "#F8F5FF",
          50: "#E0D5FF",
          100: "#C9B5FF",
          200: "#B196FF",
          300: "#9A76FF",
          400: "#8256FF",
          500: "#6B47D1",
          600: "#5337A3",
          700: "#3C2875",
          800: "#241847",
          900: "#0D091A",
        },
        red: {
          25: "#FFEEE8",
          50: "#FFD3C6",
          100: "#FFB9A3",
          200: "#ff9f81",
          300: "#FF855E",
          400: "#FF6A3C",
          500: "#ff5019",
          600: "#D14215",
          700: "#A33310",
          800: "#75250C",
          900: "#471607",
        },
        orange: {
          25: "#FFF7E8",
          50: "#FFECC6",
          100: "#FFE0A3",
          200: "#FFD481",
          300: "#FFC85E",
          400: "#FFBD3C",
          500: "#FFB119",
          600: "#D19115",
          700: "#A37110",
          800: "#75510C",
          900: "#473207",
        },
        green: {
          25: "#E8F8EF",
          50: "#C6EED8",
          100: "#A3E3C1",
          200: "#81D9A9",
          300: "#5ECF92",
          400: "#3CC47A",
          500: "#19BA63",
          600: "#159951",
          700: "#10773F",
          800: "#0C562E",
          900: "#07341C",
        },
        blue: {
          25: "#E8F4FF",
          50: "#C6E4FF",
          100: "#A4D3FF",
          200: "#82C3FF",
          300: "#60B3FF",
          400: "#3EA2FF",
          500: "#1C92FF",
          600: "#1778D1",
          700: "#125DA3",
          800: "#0D4375",
          900: "#082947",
        },

        error: {
          25: "#FFEEE8",
          50: "#FFD3C6",
          100: "#FFB9A3",
          200: "#ff9f81",
          300: "#FF855E",
          400: "#FF6A3C",
          500: "#ff5019",
          600: "#D14215",
          700: "#A33310",
          800: "#75250C",
          900: "#471607",
        },
        success: {
          25: "#E8F8EF",
          50: "#C6EED8",
          100: "#A3E3C1",
          200: "#81D9A9",
          300: "#5ECF92",
          400: "#3CC47A",
          500: "#19BA63",
          600: "#159951",
          700: "#10773F",
          800: "#0C562E",
          900: "#07341C",
        },
        warning: {
          25: "#FFF7E8",
          50: "#FFECC6",
          100: "#FFE0A3",
          200: "#FFD481",
          300: "#FFC85E",
          400: "#FFBD3C",
          500: "#FFB119",
          600: "#D19115",
          700: "#A37110",
          800: "#75510C",
          900: "#473207",
        },
        info: {
          25: "#E8F4FF",
          50: "#C6E4FF",
          100: "#A4D3FF",
          200: "#82C3FF",
          300: "#60B3FF",
          400: "#3EA2FF",
          500: "#1C92FF",
          600: "#1778D1",
          700: "#125DA3",
          800: "#0D4375",
          900: "#082947",
        },

        primary: {
          25: "#edfaf5",
          50: "#dcfbf3",
          100: "#b9ffee",
          200: "#9bffe6",
          300: "#7affdf",
          400: "#5effd7",
          DEFAULT: "#48e8c0",
          600: "#3ab597",
          700: "#318570",
          800: "#246354",
          900: "#1a473c",
        },
        secondary: {
          25: "#F8F5FF",
          50: "#E0D5FF",
          100: "#C9B5FF",
          200: "#B196FF",
          300: "#9A76FF",
          DEFAULT: "#8256FF",
          500: "#6B47D1",
          600: "#5337A3",
          700: "#3C2875",
          800: "#241847",
          900: "#0D091A",
        },
        accent: {
          25: "#F8F5FF",
          50: "#E0D5FF",
          100: "#C9B5FF",
          200: "#B196FF",
          300: "#9A76FF",
          400: "#8256FF",
          DEFAULT: "#6B47D1",
          600: "#5337A3",
          700: "#3C2875",
          800: "#241847",
          900: "#0D091A",
        },
        neutral: {
          25: "#fafafa",
          50: "#f5f5f5",
          100: "#efefef",
          200: "#dddddd",
          300: "#c3c4c3",
          400: "#b0b1b1",
          DEFAULT: "#878888",
          600: "#6c6d6d",
          700: "#404141",
          800: "#222222",
          900: "#121313",
        },
      },
      fontFamily: {
        DEFAULT: ["Inter", ...defaultTheme.fontFamily.sans],
        sans: ["Inter", ...defaultTheme.fontFamily.sans],
      },
      fontSize: {
        ...fontSizes,
      },
      fontWeight: {
        100: "100",
        200: "200",
        300: "300",
        400: "400",
        500: "500",
        600: "600",
        700: "700",
        800: "800",
        900: "900",
      },
      lineHeight: {
        "3xs": "100%",
        "2xs": "110%",
        xs: "130%",
        sm: "140%",
        md: "150%",
        lg: "170%",
      },
      scale: 16,
      letterSpacing: {
        xl: "0.3px",
        sm: "-1.5px",
        md: "0px",
        lg: "0.2px",
      },
      borderRadius: {
        sm: 4,
        md: 6,
        lg: 8,
      },
      borderWidth: {
        DEFAULT: 1,
      },
      spacing: {
        1: spacings["3xs"],
        2: spacings["2xs"],
        3: spacings.xs,
        4: spacings.sm,
        5: spacings.md,
        6: spacings.lg,
        7: spacings.xl,
        8: spacings["2xl"],
        9: spacings["3xl"],
      },
      screens: {
        xs: "360px",
        xl: "1600px",
        sm: "600px",
        md: "1024px",
        lg: "1300px",
      },
      dropShadow: {
        DEFAULT: "0px 4px 20px 0px #10121190",
      },
      typography: {
        heading: {
          1: {
            fontFamily: "Inter",
            fontWeight: "semi-bold",
            lineHeight: "110%",
            fontSize: 64,
            letterSpacing: "0px",
          },
          2: {
            fontFamily: "Inter",
            fontWeight: "semi-bold",
            lineHeight: "110%",
            fontSize: 56,
            letterSpacing: "-1.5px",
          },
          3: {
            fontFamily: "Inter",
            fontWeight: "semi-bold",
            lineHeight: "110%",
            fontSize: 48,
            letterSpacing: "-1.5px",
          },
          4: {
            fontFamily: "Inter",
            fontWeight: "semi-bold",
            lineHeight: "110%",
            fontSize: 40,
            letterSpacing: "-1.5px",
          },
          5: {
            fontFamily: "Inter",
            fontWeight: "semi-bold",
            lineHeight: "130%",
            fontSize: 36,
            letterSpacing: "-1.5px",
          },
          6: {
            fontFamily: "Inter",
            fontWeight: "semi-bold",
            lineHeight: "130%",
            fontSize: 32,
            letterSpacing: "0px",
          },
          7: {
            fontFamily: "Inter",
            fontWeight: "semi-bold",
            lineHeight: "130%",
            fontSize: 22,
            letterSpacing: "0px",
          },
        },
        subtitle: {
          1: {
            fontFamily: "Inter",
            fontWeight: "bold",
            lineHeight: "130%",
            fontSize: 32,
            letterSpacing: "0px",
          },
          2: {
            fontFamily: "Inter",
            fontWeight: "semi-bold",
            lineHeight: "130%",
            fontSize: 32,
            letterSpacing: "0px",
          },
          3: {
            fontFamily: "Inter",
            fontWeight: "regular",
            lineHeight: "130%",
            fontSize: 32,
            letterSpacing: "0px",
          },
          4: {
            fontFamily: "Inter",
            fontWeight: "bold",
            lineHeight: "130%",
            fontSize: 22,
            letterSpacing: "0px",
          },
          5: {
            fontFamily: "Inter",
            fontWeight: "semi-bold",
            lineHeight: "130%",
            fontSize: 22,
            letterSpacing: "0px",
          },
          6: {
            fontFamily: "Inter",
            fontWeight: "bold",
            lineHeight: "130%",
            fontSize: 22,
            letterSpacing: "0px",
          },
          7: {
            fontFamily: "Inter",
            fontWeight: "bold",
            lineHeight: "150%",
            fontSize: 20,
            letterSpacing: "0px",
          },
          8: {
            fontFamily: "Inter",
            fontWeight: "semi-bold",
            lineHeight: "150%",
            fontSize: 20,
            letterSpacing: "0px",
          },
          9: {
            fontFamily: "Inter",
            fontWeight: "regular",
            lineHeight: "150%",
            fontSize: 20,
            letterSpacing: "0px",
          },
          10: {
            fontFamily: "Inter",
            fontWeight: "bold",
            lineHeight: "140%",
            fontSize: 18,
            letterSpacing: "0px",
          },
          11: {
            fontFamily: "Inter",
            fontWeight: "semi-bold",
            lineHeight: "140%",
            fontSize: 18,
            letterSpacing: "0px",
          },
          12: {
            fontFamily: "Inter",
            fontWeight: "regular",
            lineHeight: "140%",
            fontSize: 18,
            letterSpacing: "0px",
          },
        },
        description: {
          1: {
            fontFamily: "Inter",
            fontWeight: "bold",
            lineHeight: "150%",
            fontSize: 22,
            letterSpacing: "0px",
          },
          2: {
            fontFamily: "Inter",
            fontWeight: "semi-bold",
            lineHeight: "150%",
            fontSize: 22,
            letterSpacing: "0px",
          },
          3: {
            fontFamily: "Inter",
            fontWeight: "regular",
            lineHeight: "150%",
            fontSize: 22,
            letterSpacing: "0px",
          },
          4: {
            fontFamily: "Inter",
            fontWeight: "bold",
            lineHeight: "150%",
            fontSize: 20,
            letterSpacing: "0px",
          },
          5: {
            fontFamily: "Inter",
            fontWeight: "semi-bold",
            lineHeight: "150%",
            fontSize: 20,
            letterSpacing: "0px",
          },
          6: {
            fontFamily: "Inter",
            fontWeight: "regular",
            lineHeight: "150%",
            fontSize: 20,
            letterSpacing: "0px",
          },
          7: {
            fontFamily: "Inter",
            fontWeight: "bold",
            lineHeight: "150%",
            fontSize: 18,
            letterSpacing: "0px",
          },
          8: {
            fontFamily: "Inter",
            fontWeight: "semi-bold",
            lineHeight: "150%",
            fontSize: 18,
            letterSpacing: "0px",
          },
          9: {
            fontFamily: "Inter",
            fontWeight: "regular",
            lineHeight: "150%",
            fontSize: 18,
            letterSpacing: "0px",
          },
        },
        body: {
          1: {
            fontFamily: "Inter",
            fontWeight: "bold",
            lineHeight: "150%",
            fontSize: 20,
            letterSpacing: "0px",
          },
          2: {
            fontFamily: "Inter",
            fontWeight: "semi-bold",
            lineHeight: "150%",
            fontSize: 20,
            letterSpacing: "0px",
          },
          3: {
            fontFamily: "Inter",
            fontWeight: "regular",
            lineHeight: "150%",
            fontSize: 20,
            letterSpacing: "0px",
          },
          4: {
            fontFamily: "Inter",
            fontWeight: "bold",
            lineHeight: "140%",
            fontSize: 16,
            letterSpacing: "0px",
          },
          5: {
            fontFamily: "Inter",
            fontWeight: "semi-bold",
            lineHeight: "140%",
            fontSize: 16,
            letterSpacing: "0px",
          },
          6: {
            fontFamily: "Inter",
            fontWeight: "regular",
            lineHeight: "140%",
            fontSize: 16,
            letterSpacing: "0px",
          },
          7: {
            fontFamily: "Inter",
            fontWeight: "bold",
            lineHeight: "140%",
            fontSize: 14,
            letterSpacing: "0px",
          },
          8: {
            fontFamily: "Inter",
            fontWeight: "semi-bold",
            lineHeight: "140%",
            fontSize: 14,
            letterSpacing: "0px",
          },
          9: {
            fontFamily: "Inter",
            fontWeight: "regular",
            lineHeight: "140%",
            fontSize: 14,
            letterSpacing: "0px",
          },
          10: {
            fontFamily: "Inter",
            fontWeight: "regular",
            lineHeight: "140%",
            fontSize: 12,
            letterSpacing: "0px",
          },
        },
        overline: {
          1: {
            fontFamily: "Inter",
            fontWeight: "regular",
            lineHeight: "170%",
            fontSize: 12,
            letterSpacing: "0px",
          },
          2: {
            fontFamily: "Inter",
            fontWeight: "regular",
            lineHeight: "170%",
            fontSize: 10,
            letterSpacing: "0px",
          },
        },
        button: {
          1: {
            fontFamily: "Inter",
            fontWeight: "semi-bold",
            lineHeight: "100%",
            fontSize: 18,
            letterSpacing: "0.3px",
          },
          2: {
            fontFamily: "Inter",
            fontWeight: "semi-bold",
            lineHeight: "100%",
            fontSize: 16,
            letterSpacing: "0.3px",
          },
          3: {
            fontFamily: "Inter",
            fontWeight: "semi-bold",
            lineHeight: "100%",
            fontSize: 14,
            letterSpacing: "0.2px",
          },
        },
        link: {
          1: {
            fontFamily: "Inter",
            fontWeight: "medium",
            lineHeight: "140%",
            fontSize: 16,
            letterSpacing: "0px",
          },
          2: {
            fontFamily: "Inter",
            fontWeight: "medium",
            lineHeight: "140%",
            fontSize: 14,
            letterSpacing: "0px",
          },
          3: {
            fontFamily: "Inter",
            fontWeight: "medium",
            lineHeight: "140%",
            fontSize: 12,
            letterSpacing: "0px",
          },
        },
        tagline: {
          1: {
            fontFamily: "Inter",
            fontWeight: "bold",
            lineHeight: "150%",
            fontSize: 18,
            letterSpacing: "0px",
          },
          2: {
            fontFamily: "Inter",
            fontWeight: "semi-bold",
            lineHeight: "150%",
            fontSize: 18,
            letterSpacing: "0px",
          },
          3: {
            fontFamily: "Inter",
            fontWeight: "medium",
            lineHeight: "150%",
            fontSize: 18,
            letterSpacing: "0px",
          },
          4: {
            fontFamily: "Inter",
            fontWeight: "bold",
            lineHeight: "150%",
            fontSize: 16,
            letterSpacing: "0px",
          },
          5: {
            fontFamily: "Inter",
            fontWeight: "semi-bold",
            lineHeight: "150%",
            fontSize: 16,
            letterSpacing: "0px",
          },
          6: {
            fontFamily: "Inter",
            fontWeight: "medium",
            lineHeight: "150%",
            fontSize: 16,
            letterSpacing: "0px",
          },
          7: {
            fontFamily: "Inter",
            fontWeight: "bold",
            lineHeight: "150%",
            fontSize: 14,
            letterSpacing: "0px",
          },
          8: {
            fontFamily: "Inter",
            fontWeight: "semi-bold",
            lineHeight: "150%",
            fontSize: 14,
            letterSpacing: "0px",
          },
          9: {
            fontFamily: "Inter",
            fontWeight: "medium",
            lineHeight: "150%",
            fontSize: 14,
            letterSpacing: "0px",
          },
          10: {
            fontFamily: "Inter",
            fontWeight: "bold",
            lineHeight: "150%",
            fontSize: 12,
            letterSpacing: "0px",
          },
          11: {
            fontFamily: "Inter",
            fontWeight: "semi-bold",
            lineHeight: "150%",
            fontSize: 12,
            letterSpacing: "0px",
          },
          12: {
            fontFamily: "Inter",
            fontWeight: "medium",
            lineHeight: "150%",
            fontSize: 12,
            letterSpacing: "0px",
          },
        },
        menuNavigation: {
          1: {
            fontFamily: "Inter",
            fontWeight: "regular",
            lineHeight: "150%",
            fontSize: 16,
            letterSpacing: "0px",
          },
          2: {
            fontFamily: "Inter",
            fontWeight: "medium",
            lineHeight: "150%",
            fontSize: 14,
            letterSpacing: "0px",
          },
          3: {
            fontFamily: "Inter",
            fontWeight: "medium",
            lineHeight: "150%",
            fontSize: 12,
            letterSpacing: "0px",
          },
        },
      },
      form: {
        input: {
          border: {
            disabled: {
              color: "#222222",
              width: "1px",
              style: "solid",
            },
            focused: {
              color: "#f3f3f3",
              width: "1px",
              style: "solid",
            },
            error: {
              focused: {
                color: "#FF855E",
                width: "1px",
                style: "solid",
              },
              default: {
                color: "#A33310",
                width: "1px",
                style: "solid",
              },
            },
            default: {
              color: "#404141",
              width: "1px",
              style: "solid",
            },
          },
        },
        search: {
          border: {
            disabled: {
              color: "#222222",
              width: "1px",
              style: "solid",
            },
            focused: {
              color: "#f3f3f3",
              width: "1px",
              style: "solid",
            },
            error: {
              focused: {
                color: "#FF855E",
                width: "1px",
                style: "solid",
              },
              neutral: {
                color: "#A33310",
                width: "1px",
                style: "solid",
              },
            },
            default: {
              color: "#404141",
              width: "1px",
              style: "solid",
            },
          },
        },
      },
    },
  },
};
